In [16]:
# Cellule 1 : Imports
import pandas as pd
import numpy as np
from datetime import datetime

# Cellule 2 : Chargement des données
print("Chargement des données...")
# Chemin adapté pour un notebook dans le dossier notebooks
df = pd.read_csv('../data/text/products_asos.csv')

# Affichage de l'état initial
print("\nÉtat initial:")
print(f"Nombre de lignes: {len(df)}")
print(f"Colonnes: {df.columns.tolist()}")

# Cellule 3 : Nettoyage des types de données
# Conversion des prix en float
price_columns = ['price']  
for col in price_columns:
    if col in df.columns:
        # Suppression des symboles monétaires et espaces
        df[col] = df[col].astype(str).str.replace('£', '').str.replace('$', '').str.replace('€', '')
        df[col] = df[col].str.replace(',', '').str.strip()
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Cellule 4 : Nettoyage du texte
text_columns = ['name', 'description', 'category']
for col in text_columns:
    if col in df.columns:
        # Conversion en minuscules
        df[col] = df[col].str.lower()
        # Suppression des caractères spéciaux
        df[col] = df[col].str.replace(r'[^\w\s]', ' ', regex=True)
        # Suppression des espaces multiples
        df[col] = df[col].str.replace(r'\s+', ' ', regex=True)
        # Suppression des espaces début/fin
        df[col] = df[col].str.strip()

# Cellule 5 : Standardisation des catégories
if 'category' in df.columns:
    category_mapping = {
        'mens': 'men',
        'womens': 'women',
        't-shirt': 'tshirt',
        'tshirts': 'tshirt',
    }
    df['category'] = df['category'].map(category_mapping).fillna(df['category'])

# Cellule 6 : Gestion des outliers
# Pour les prix
if 'price' in df.columns:
    Q1 = df['price'].quantile(0.25)
    Q3 = df['price'].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    print("Statistiques des prix avant filtrage des outliers:")
    print(f"Minimum: {df['price'].min()}")
    print(f"Maximum: {df['price'].max()}")
    print(f"Nombre de produits: {len(df)}")
    
    df = df[(df['price'] >= lower_bound) & (df['price'] <= upper_bound)]
    
    print("\nAprès filtrage:")
    print(f"Minimum: {df['price'].min()}")
    print(f"Maximum: {df['price'].max()}")
    print(f"Nombre de produits: {len(df)}")

# Cellule 7 : Gestion des valeurs manquantes
# Affichage des valeurs manquantes
print("Valeurs manquantes par colonne:")
print(df.isnull().sum())

# Pour les colonnes numériques
numeric_columns = df.select_dtypes(include=[np.number]).columns
for col in numeric_columns:
    median_value = df[col].median()
    df[col] = df[col].fillna(median_value)

# Pour les colonnes catégorielles
categorical_columns = df.select_dtypes(include=['object']).columns
for col in categorical_columns:
    mode_value = df[col].mode()[0]
    df[col] = df[col].fillna(mode_value)

# Cellule 8 : Suppression des doublons
print("Nombre de lignes avant suppression des doublons:", len(df))
df = df.drop_duplicates()
print("Nombre de lignes après suppression des doublons:", len(df))

# Cellule 9 : Vérification finale et sauvegarde
# Vérification finale
print("\nRésumé des données nettoyées:")
print(df.info())
print("\nAperçu des données:")
print(df.head())

# Sauvegarde
output_path = '../data/text/products_asos_cleaned_full.csv'
df.to_csv(output_path, index=False)
print(f"\nDonnées nettoyées sauvegardées dans: {output_path}")

Chargement des données...

État initial:
Nombre de lignes: 30845
Colonnes: ['url', 'name', 'size', 'category', 'price', 'color', 'sku', 'description', 'images']
Statistiques des prix avant filtrage des outliers:
Minimum: 4.5
Maximum: 550.0
Nombre de produits: 30845

Après filtrage:
Minimum: 4.5
Maximum: 100.0
Nombre de produits: 17169
Valeurs manquantes par colonne:
url            0
name           0
size           0
category       0
price          0
color          0
sku            0
description    0
images         0
dtype: int64
Nombre de lignes avant suppression des doublons: 17169
Nombre de lignes après suppression des doublons: 16953

Résumé des données nettoyées:
<class 'pandas.core.frame.DataFrame'>
Index: 16953 entries, 0 to 30844
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   url          16953 non-null  object
 1   name         16953 non-null  object
 2   size         16953 non-null  object
 3   category     16953 non-null  object
 4   price        16953 non-null  float64
 5   color        16953 non-null  object
 6   sku          16953 non-null  float64
 7   description  16953 non-null  object
 8   images       16953 non-null  object
dtypes: float64(2), object(7)
memory usage: 1.3+ MB
None

Aperçu des données:
                                                 url  \
0  https://www.asos.com/stradivarius/stradivarius...
1  https://www.asos.com/stradivarius/stradivarius...
2  https://www.asos.com/asos-design/asos-design-l...
3  https://www.asos.com/new-look/new-look-trench-...
4  https://www.asos.com/stradivarius/stradivarius...

                                             name  \
0                   new look trench coat in camel
1                   new look trench coat in camel
2                   new look trench coat in camel
3                   new look trench coat in camel
4  stradivarius double breasted wool coat in grey

                                                size  \
0  UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...
1  UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...
2  UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...
3  UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...
4  XS - UK 6,S - UK 8,M - UK 10,L - UK 12,XL - UK 14

                                         category  price    color  \
0                   new look trench coat in camel  49.99  Neutral
1                   new look trench coat in camel  49.99  Neutral
2                   new look trench coat in camel  49.99  Neutral
3                   new look trench coat in camel  49.99  Neutral
4  stradivarius double breasted wool coat in grey  59.99     GREY

           sku                                        description  \
0  126704571.0  product details coats jackets by new looklow k...
1  126704571.0  product details coats jackets by new looklow k...
2  126704571.0  product details coats jackets by new looklow k...
3  126704571.0  product details coats jackets by new looklow k...
4  123650194.0  product details coats jackets by stradivariusj...

                                              images
0  ['https://images.asos-media.com/products/new-l...
1  ['https://images.asos-media.com/products/new-l...
2  ['https://images.asos-media.com/products/new-l...
3  ['https://images.asos-media.com/products/new-l...
4  ['https://images.asos-media.com/products/strad...

Données nettoyées sauvegardées dans: ../data/text/products_asos_cleaned_full.csv

In [17]:
# Cellule 1 : Imports
import pandas as pd
import numpy as np
from datetime import datetime

# Cellule 2 : Chargement des données
print("Chargement des données...")
# Chemin adapté pour un notebook dans le dossier notebooks
df = pd.read_csv('../data/text/mr-porter.csv')

# Affichage de l'état initial
print("\nÉtat initial:")
print(f"Nombre de lignes: {len(df)}")
print(f"Colonnes: {df.columns.tolist()}")

# Cellule 3 : Nettoyage des types de données
# Conversion des prix en float
price_columns = ['price']  
for col in price_columns:
    if col in df.columns:
        # Suppression des symboles monétaires et espaces
        df[col] = df[col].astype(str).str.replace('£', '').str.replace('$', '').str.replace('€', '')
        df[col] = df[col].str.replace(',', '').str.strip()
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Cellule 4 : Nettoyage du texte
text_columns = ['name', 'description', 'category']
for col in text_columns:
    if col in df.columns:
        # Conversion en minuscules
        df[col] = df[col].str.lower()
        # Suppression des caractères spéciaux
        df[col] = df[col].str.replace(r'[^\w\s]', ' ', regex=True)
        # Suppression des espaces multiples
        df[col] = df[col].str.replace(r'\s+', ' ', regex=True)
        # Suppression des espaces début/fin
        df[col] = df[col].str.strip()

# Cellule 5 : Standardisation des catégories
if 'category' in df.columns:
    category_mapping = {
        'mens': 'men',
        'womens': 'women',
        't-shirt': 'tshirt',
        'tshirts': 'tshirt',
    }
    df['category'] = df['category'].map(category_mapping).fillna(df['category'])

# Cellule 6 : Gestion des outliers
# Pour les prix
if 'price' in df.columns:
    Q1 = df['price'].quantile(0.25)
    Q3 = df['price'].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    print("Statistiques des prix avant filtrage des outliers:")
    print(f"Minimum: {df['price'].min()}")
    print(f"Maximum: {df['price'].max()}")
    print(f"Nombre de produits: {len(df)}")
    
    df = df[(df['price'] >= lower_bound) & (df['price'] <= upper_bound)]
    
    print("\nAprès filtrage:")
    print(f"Minimum: {df['price'].min()}")
    print(f"Maximum: {df['price'].max()}")
    print(f"Nombre de produits: {len(df)}")

# Cellule 7 : Gestion des valeurs manquantes
# Affichage des valeurs manquantes
print("Valeurs manquantes par colonne:")
print(df.isnull().sum())

# Pour les colonnes numériques
numeric_columns = df.select_dtypes(include=[np.number]).columns
for col in numeric_columns:
    median_value = df[col].median()
    df[col] = df[col].fillna(median_value)

# Pour les colonnes catégorielles
categorical_columns = df.select_dtypes(include=['object']).columns
for col in categorical_columns:
    mode_value = df[col].mode()[0]
    df[col] = df[col].fillna(mode_value)

# Cellule 8 : Suppression des doublons
print("Nombre de lignes avant suppression des doublons:", len(df))
df = df.drop_duplicates()
print("Nombre de lignes après suppression des doublons:", len(df))

# Cellule 9 : Vérification finale et sauvegarde
# Vérification finale
print("\nRésumé des données nettoyées:")
print(df.info())
print("\nAperçu des données:")
print(df.head())

# Sauvegarde
output_path = '../data/text/mr-porter_cleaned_full.csv'
df.to_csv(output_path, index=False)
print(f"\nDonnées nettoyées sauvegardées dans: {output_path}")

Chargement des données...

État initial:
Nombre de lignes: 20347
Colonnes: ['brand', 'description', 'price_usd', 'type']
Valeurs manquantes par colonne:
brand          0
description    0
price_usd      0
type           0
dtype: int64
Nombre de lignes avant suppression des doublons: 20347
Nombre de lignes après suppression des doublons: 20296

Résumé des données nettoyées:
<class 'pandas.core.frame.DataFrame'>
Index: 20296 entries, 0 to 20346
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   brand        20296 non-null  object
 1   description  20296 non-null  object
 2   price_usd    20296 non-null  int64
 3   type         20296 non-null  object
dtypes: int64(1), object(3)
memory usage: 792.8+ KB
None

Aperçu des données:
            brand                                        description  \
0       VALENTINO  m way rockstud beatle patent leather chelsea b...
1         THE ROW                  owen suede trimmed nylon sneakers
2  MANOLO BLAHNIK          ellis full grain leather slip on sneakers
3    R.M.WILLIAMS                    craftsman leather chelsea boots
4  MANOLO BLAHNIK          kensington shearling lined suede slippers

   price_usd   type
0       1550  shoes
1        830  shoes
2        725  shoes
3        540  shoes
4        775  shoes

Données nettoyées sauvegardées dans: ../data/text/mr-porter_cleaned_full.csv

In [18]:
# Cellule 1 : Imports
import pandas as pd
import numpy as np
from datetime import datetime

# Cellule 2 : Chargement des données
print("Chargement des données...")
# Chemin adapté pour un notebook dans le dossier notebooks
df = pd.read_csv('../data/text/net-a-porter.csv')

# Affichage de l'état initial
print("\nÉtat initial:")
print(f"Nombre de lignes: {len(df)}")
print(f"Colonnes: {df.columns.tolist()}")

# Cellule 3 : Nettoyage des types de données
# Conversion des prix en float
price_columns = ['price']  
for col in price_columns:
    if col in df.columns:
        # Suppression des symboles monétaires et espaces
        df[col] = df[col].astype(str).str.replace('£', '').str.replace('$', '').str.replace('€', '')
        df[col] = df[col].str.replace(',', '').str.strip()
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Cellule 4 : Nettoyage du texte
text_columns = ['name', 'description', 'category']
for col in text_columns:
    if col in df.columns:
        # Conversion en minuscules
        df[col] = df[col].str.lower()
        # Suppression des caractères spéciaux
        df[col] = df[col].str.replace(r'[^\w\s]', ' ', regex=True)
        # Suppression des espaces multiples
        df[col] = df[col].str.replace(r'\s+', ' ', regex=True)
        # Suppression des espaces début/fin
        df[col] = df[col].str.strip()

# Cellule 5 : Standardisation des catégories
if 'category' in df.columns:
    category_mapping = {
        'mens': 'men',
        'womens': 'women',
        't-shirt': 'tshirt',
        'tshirts': 'tshirt',
    }
    df['category'] = df['category'].map(category_mapping).fillna(df['category'])

# Cellule 6 : Gestion des outliers
# Pour les prix
if 'price' in df.columns:
    Q1 = df['price'].quantile(0.25)
    Q3 = df['price'].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    print("Statistiques des prix avant filtrage des outliers:")
    print(f"Minimum: {df['price'].min()}")
    print(f"Maximum: {df['price'].max()}")
    print(f"Nombre de produits: {len(df)}")
    
    df = df[(df['price'] >= lower_bound) & (df['price'] <= upper_bound)]
    
    print("\nAprès filtrage:")
    print(f"Minimum: {df['price'].min()}")
    print(f"Maximum: {df['price'].max()}")
    print(f"Nombre de produits: {len(df)}")

# Cellule 7 : Gestion des valeurs manquantes
# Affichage des valeurs manquantes
print("Valeurs manquantes par colonne:")
print(df.isnull().sum())

# Pour les colonnes numériques
numeric_columns = df.select_dtypes(include=[np.number]).columns
for col in numeric_columns:
    median_value = df[col].median()
    df[col] = df[col].fillna(median_value)

# Pour les colonnes catégorielles
categorical_columns = df.select_dtypes(include=['object']).columns
for col in categorical_columns:
    mode_value = df[col].mode()[0]
    df[col] = df[col].fillna(mode_value)

# Cellule 8 : Suppression des doublons
print("Nombre de lignes avant suppression des doublons:", len(df))
df = df.drop_duplicates()
print("Nombre de lignes après suppression des doublons:", len(df))

# Cellule 9 : Vérification finale et sauvegarde
# Vérification finale
print("\nRésumé des données nettoyées:")
print(df.info())
print("\nAperçu des données:")
print(df.head())

# Sauvegarde
output_path = '../data/text/net-a-porter_cleaned_full.csv'
df.to_csv(output_path, index=False)
print(f"\nDonnées nettoyées sauvegardées dans: {output_path}")

Chargement des données...

État initial:
Nombre de lignes: 23161
Colonnes: ['brand', 'description', 'price_usd', 'type']
Valeurs manquantes par colonne:
brand          0
description    0
price_usd      0
type           0
dtype: int64
Nombre de lignes avant suppression des doublons: 23161
Nombre de lignes après suppression des doublons: 23131

Résumé des données nettoyées:
<class 'pandas.core.frame.DataFrame'>
Index: 23131 entries, 0 to 23160
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   brand        23131 non-null  object
 1   description  23131 non-null  object
 2   price_usd    23131 non-null  int64
 3   type         23131 non-null  object
dtypes: int64(1), object(3)
memory usage: 903.6+ KB
None

Aperçu des données:
                brand                                        description  \
0             MONCLER                  vistule quilted shell down jacket
1  GUEST IN RESIDENCE                           grizzly cashmere sweater
2               CHLOÉ     net sustain high rise boyfriend recycled jeans
3   OSCAR DE LA RENTA                  embellished wool blend mini dress
4          ZIMMERMANN  net sustain crochet trimmed floral print linen...

   price_usd      type
0       1750  clothing
1        545  clothing
2       1290  clothing
3       2590  clothing
4        850  clothing

Données nettoyées sauvegardées dans: ../data/text/net-a-porter_cleaned_full.csv

In [19]:
# Cellule 1 : Imports
import pandas as pd
import numpy as np
from datetime import datetime

# Cellule 2 : Chargement des données
print("Chargement des données...")
# Chemin adapté pour un notebook dans le dossier notebooks
df = pd.read_csv('../data/text/ssense_dataset.csv')

# Affichage de l'état initial
print("\nÉtat initial:")
print(f"Nombre de lignes: {len(df)}")
print(f"Colonnes: {df.columns.tolist()}")

# Cellule 3 : Nettoyage des types de données
# Conversion des prix en float
price_columns = ['price']  
for col in price_columns:
    if col in df.columns:
        # Suppression des symboles monétaires et espaces
        df[col] = df[col].astype(str).str.replace('£', '').str.replace('$', '').str.replace('€', '')
        df[col] = df[col].str.replace(',', '').str.strip()
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Cellule 4 : Nettoyage du texte
text_columns = ['name', 'description', 'category']
for col in text_columns:
    if col in df.columns:
        # Conversion en minuscules
        df[col] = df[col].str.lower()
        # Suppression des caractères spéciaux
        df[col] = df[col].str.replace(r'[^\w\s]', ' ', regex=True)
        # Suppression des espaces multiples
        df[col] = df[col].str.replace(r'\s+', ' ', regex=True)
        # Suppression des espaces début/fin
        df[col] = df[col].str.strip()

# Cellule 5 : Standardisation des catégories
if 'category' in df.columns:
    category_mapping = {
        'mens': 'men',
        'womens': 'women',
        't-shirt': 'tshirt',
        'tshirts': 'tshirt',
    }
    df['category'] = df['category'].map(category_mapping).fillna(df['category'])

# Cellule 6 : Gestion des outliers
# Pour les prix
if 'price' in df.columns:
    Q1 = df['price'].quantile(0.25)
    Q3 = df['price'].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    print("Statistiques des prix avant filtrage des outliers:")
    print(f"Minimum: {df['price'].min()}")
    print(f"Maximum: {df['price'].max()}")
    print(f"Nombre de produits: {len(df)}")
    
    df = df[(df['price'] >= lower_bound) & (df['price'] <= upper_bound)]
    
    print("\nAprès filtrage:")
    print(f"Minimum: {df['price'].min()}")
    print(f"Maximum: {df['price'].max()}")
    print(f"Nombre de produits: {len(df)}")

# Cellule 7 : Gestion des valeurs manquantes
# Affichage des valeurs manquantes
print("Valeurs manquantes par colonne:")
print(df.isnull().sum())

# Pour les colonnes numériques
numeric_columns = df.select_dtypes(include=[np.number]).columns
for col in numeric_columns:
    median_value = df[col].median()
    df[col] = df[col].fillna(median_value)

# Pour les colonnes catégorielles
categorical_columns = df.select_dtypes(include=['object']).columns
for col in categorical_columns:
    mode_value = df[col].mode()[0]
    df[col] = df[col].fillna(mode_value)

# Cellule 8 : Suppression des doublons
print("Nombre de lignes avant suppression des doublons:", len(df))
df = df.drop_duplicates()
print("Nombre de lignes après suppression des doublons:", len(df))

# Cellule 9 : Vérification finale et sauvegarde
# Vérification finale
print("\nRésumé des données nettoyées:")
print(df.info())
print("\nAperçu des données:")
print(df.head())

# Sauvegarde
output_path = '../data/text/ssense_cleaned_full.csv'
df.to_csv(output_path, index=False)
print(f"\nDonnées nettoyées sauvegardées dans: {output_path}")

Chargement des données...

État initial:
Nombre de lignes: 19919
Colonnes: ['brand', 'description', 'price_usd', 'type']
Valeurs manquantes par colonne:
brand          0
description    0
price_usd      0
type           0
dtype: int64
Nombre de lignes avant suppression des doublons: 19919
Nombre de lignes après suppression des doublons: 19918

Résumé des données nettoyées:
<class 'pandas.core.frame.DataFrame'>
Index: 19918 entries, 0 to 19918
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   brand        19918 non-null  object
 1   description  19918 non-null  object
 2   price_usd    19918 non-null  int64
 3   type         19918 non-null  object
dtypes: int64(1), object(3)
memory usage: 778.0+ KB
None

Aperçu des données:
        brand                                       description  price_usd  \
0  Rick Owens                   black moncler edition down coat       2585
1  Rick Owens          black moncler edition cyclopic down coat       2405
2  Rick Owens        black moncler edition cyclopic down jacket       3160
3  Rick Owens             taupe green moncler edition down coat       3505
4  Rick Owens  taupe green moncler edition cyclopic down jacket       2885

   type
0  mens
1  mens
2  mens
3  mens
4  mens

Données nettoyées sauvegardées dans: ../data/text/ssense_cleaned_full.csv

In [20]:
# Cellule 1 : Imports
import pandas as pd
import numpy as np
from datetime import datetime

# Cellule 2 : Chargement des données
print("Chargement des données...")
# Chemin adapté pour un notebook dans le dossier notebooks
df = pd.read_csv('../data/text/vestiaire.csv')

# Affichage de l'état initial
print("\nÉtat initial:")
print(f"Nombre de lignes: {len(df)}")
print(f"Colonnes: {df.columns.tolist()}")

# Cellule 3 : Nettoyage des types de données
# Conversion des prix en float
price_columns = ['price']  
for col in price_columns:
    if col in df.columns:
        # Suppression des symboles monétaires et espaces
        df[col] = df[col].astype(str).str.replace('£', '').str.replace('$', '').str.replace('€', '')
        df[col] = df[col].str.replace(',', '').str.strip()
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Cellule 4 : Nettoyage du texte
text_columns = ['name', 'description', 'category']
for col in text_columns:
    if col in df.columns:
        # Conversion en minuscules
        df[col] = df[col].str.lower()
        # Suppression des caractères spéciaux
        df[col] = df[col].str.replace(r'[^\w\s]', ' ', regex=True)
        # Suppression des espaces multiples
        df[col] = df[col].str.replace(r'\s+', ' ', regex=True)
        # Suppression des espaces début/fin
        df[col] = df[col].str.strip()

# Cellule 5 : Standardisation des catégories
if 'category' in df.columns:
    category_mapping = {
        'mens': 'men',
        'womens': 'women',
        't-shirt': 'tshirt',
        'tshirts': 'tshirt',
    }
    df['category'] = df['category'].map(category_mapping).fillna(df['category'])

# Cellule 6 : Gestion des outliers
# Pour les prix
if 'price' in df.columns:
    Q1 = df['price'].quantile(0.25)
    Q3 = df['price'].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    print("Statistiques des prix avant filtrage des outliers:")
    print(f"Minimum: {df['price'].min()}")
    print(f"Maximum: {df['price'].max()}")
    print(f"Nombre de produits: {len(df)}")
    
    df = df[(df['price'] >= lower_bound) & (df['price'] <= upper_bound)]
    
    print("\nAprès filtrage:")
    print(f"Minimum: {df['price'].min()}")
    print(f"Maximum: {df['price'].max()}")
    print(f"Nombre de produits: {len(df)}")

# Cellule 7 : Gestion des valeurs manquantes
# Affichage des valeurs manquantes
print("Valeurs manquantes par colonne:")
print(df.isnull().sum())

# Pour les colonnes numériques
numeric_columns = df.select_dtypes(include=[np.number]).columns
for col in numeric_columns:
    median_value = df[col].median()
    df[col] = df[col].fillna(median_value)

# Pour les colonnes catégorielles
categorical_columns = df.select_dtypes(include=['object']).columns
for col in categorical_columns:
    mode_value = df[col].mode()[0]
    df[col] = df[col].fillna(mode_value)

# Cellule 8 : Suppression des doublons
print("Nombre de lignes avant suppression des doublons:", len(df))
df = df.drop_duplicates()
print("Nombre de lignes après suppression des doublons:", len(df))

# Cellule 9 : Vérification finale et sauvegarde
# Vérification finale
print("\nRésumé des données nettoyées:")
print(df.info())
print("\nAperçu des données:")
print(df.head())

# Sauvegarde
output_path = '../data/text/vestiaire_cleaned_full.csv'
df.to_csv(output_path, index=False)
print(f"\nDonnées nettoyées sauvegardées dans: {output_path}")

Chargement des données...

État initial:
Nombre de lignes: 900514
Colonnes: ['product_id', 'product_type', 'product_name', 'product_description', 'product_keywords', 'product_gender_target', 'product_category', 'product_season', 'product_condition', 'product_like_count', 'sold', 'reserved', 'available', 'in_stock', 'should_be_gone', 'brand_id', 'brand_name', 'brand_url', 'product_material', 'product_color', 'price_usd', 'seller_price', 'seller_earning', 'seller_badge', 'has_cross_border_fees', 'buyers_fees', 'warehouse_name', 'seller_id', 'seller_username', 'usually_ships_within', 'seller_country', 'seller_products_sold', 'seller_num_products_listed', 'seller_community_rank', 'seller_num_followers', 'seller_pass_rate']
Valeurs manquantes par colonne:
product_id                         0
product_type                       0
product_name                       0
product_description                7
product_keywords                1183
product_gender_target              0
product_category                1183
product_season                     2
product_condition                  0
product_like_count                 0
sold                               0
reserved                           0
available                          0
in_stock                           0
should_be_gone                     0
brand_id                           0
brand_name                         0
brand_url                          0
product_material                   4
product_color                      1
price_usd                          0
seller_price                       0
seller_earning                     0
seller_badge                       0
has_cross_border_fees          13736
buyers_fees                    13736
warehouse_name                     0
seller_id                          0
seller_username                   39
usually_ships_within          154791
seller_country                     0
seller_products_sold               0
seller_num_products_listed         0
seller_community_rank              0
seller_num_followers               0
seller_pass_rate                   0
dtype: int64

/var/folders/vq/7f683s5n6990zmj58mg4vms40000gn/T/ipykernel_31918/3711839390.py:85: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(mode_value)

Nombre de lignes avant suppression des doublons: 900514
Nombre de lignes après suppression des doublons: 900514

Résumé des données nettoyées:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900514 entries, 0 to 900513
Data columns (total 36 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   product_id                  900514 non-null  int64
 1   product_type                900514 non-null  object
 2   product_name                900514 non-null  object
 3   product_description         900514 non-null  object
 4   product_keywords            900514 non-null  object
 5   product_gender_target       900514 non-null  object
 6   product_category            900514 non-null  object
 7   product_season              900514 non-null  object
 8   product_condition           900514 non-null  object
 9   product_like_count          900514 non-null  float64
 10  sold                        900514 non-null  bool
 11  reserved                    900514 non-null  bool
 12  available                   900514 non-null  bool
 13  in_stock                    900514 non-null  bool
 14  should_be_gone              900514 non-null  bool
 15  brand_id                    900514 non-null  int64
 16  brand_name                  900514 non-null  object
 17  brand_url                   900514 non-null  object
 18  product_material            900514 non-null  object
 19  product_color               900514 non-null  object
 20  price_usd                   900514 non-null  float64
 21  seller_price                900514 non-null  float64
 22  seller_earning              900514 non-null  float64
 23  seller_badge                900514 non-null  object
 24  has_cross_border_fees       900514 non-null  bool
 25  buyers_fees                 900514 non-null  float64
 26  warehouse_name              900514 non-null  object
 27  seller_id                   900514 non-null  int64
 28  seller_username             900514 non-null  object
 29  usually_ships_within        900514 non-null  object
 30  seller_country              900514 non-null  object
 31  seller_products_sold        900514 non-null  float64
 32  seller_num_products_listed  900514 non-null  float64
 33  seller_community_rank       900514 non-null  float64
 34  seller_num_followers        900514 non-null  float64
 35  seller_pass_rate            900514 non-null  float64
dtypes: bool(6), float64(10), int64(3), object(17)
memory usage: 211.3+ MB
None

Aperçu des données:
   product_id            product_type  \
0    43247626         Wool mini skirt
1    43247441                  Jacket
2    43246517               Wool coat
3    43246507              Mini skirt
4    43246417  Vegan leather trousers

                                        product_name  \
0  Wool mini skirt Miu Miu Grey size S Internatio...
1      Jacket Barbara Bui Navy size 42 FR in Cotton
2  Wool coat Comme Des Garcons White size S Inter...
3     Mini skirt MSGM Black size 38 IT in Polyester
4  Vegan leather trousers LVIR Black size 36 FR i...

                                 product_description  \
0  Miu Miu – Pleated mini skirt Size: 36 (S)  Wai...
1  For selling nice women's suit Barbara Bui size...
2  Magnificent boiled wool coat. I bought it in t...
3  MSGM Skirt Black Printed Raw-Edge & Embroidere...
4  LVIR black grained faux leather trousers size ...

               product_keywords product_gender_target product_category  \
0           Miu Miu Wool Skirts                 Women   Women Clothing
1    Barbara Bui Cotton Jackets                 Women   Women Clothing
2  Comme Des Garcons Wool Coats                 Women   Women Clothing
3         MSGM Polyester Skirts                 Women   Women Clothing
4   LVIR Vegan leather Trousers                 Women   Women Clothing

    product_season    product_condition  product_like_count  ...  \
0  Autumn / Winter           Never worn                34.0  ...
1      All seasons  Very good condition                 1.0  ...
2  Autumn / Winter  Very good condition                 2.0  ...
3      All seasons  Very good condition                 0.0  ...
4      All seasons  Very good condition                 1.0  ...

   warehouse_name  seller_id   seller_username  usually_ships_within  \
0       Tourcoing   25775970   vitalii25775970              1-2 days
1       Tourcoing   13698770    olivia13698770              1-2 days
2       Tourcoing    6042365    cecilia6042365              1-2 days
3        Brooklyn   13172949  gretchen13172949              1-2 days
4         Crawley    2578605        crunchykat              3-5 days

   seller_country  seller_products_sold seller_num_products_listed  \
0         Germany                   3.0                       14.0
1         Belgium                   0.0                        0.0
2           Spain                  58.0                       69.0
3   United States                  63.0                      274.0
4  United Kingdom                  19.0                       14.0

  seller_community_rank seller_num_followers seller_pass_rate
0                   0.0                 13.0              0.0
1                   0.0                  8.0              0.0
2                   0.0                 62.0             96.0
3              126346.0                131.0             96.0
4              102821.0                 40.0             89.0

[5 rows x 36 columns]

Données nettoyées sauvegardées dans: ../data/text/vestiaire_cleaned_full.csv

Nettoyage dataset sales

In [21]:
# Dans une première cellule de notebook
import pandas as pd

# Chargement du fichier mock
df_mock = pd.read_csv('../data/stats/mock_fashion_data_uk_us.csv')

# Aperçu de la structure
print("Colonnes présentes :")
print(df_mock.columns.tolist())
print("\nPremières lignes :")
print(df_mock.head())
print("\nInformations sur les types de données :")
print(df_mock.info())

Colonnes présentes :
['Product Name', 'Price', 'Brand', 'Category', 'Description', 'Rating', 'Review Count', 'Style Attributes', 'Total Sizes', 'Available Sizes', 'Color', 'Purchase History', 'Age', 'Fashion Magazines', 'Fashion Influencers', 'Season', 'Time Period Highest Purchase', 'Customer Reviews', 'Social Media Comments', 'feedback']

Premières lignes :
  Product Name      Price              Brand   Category Description    Rating  \
0         T5D3  97.509966       Ralph Lauren   Footwear         Bad  1.421706
1         Y0V7  52.341277          Ted Baker       Tops    Not Good  1.037677
2         N9Q4  15.430975             Jigsaw   Footwear    Very Bad  3.967106
3         V2T6  81.116542  Alexander McQueen  Outerwear    Not Good  2.844659
4         S7Y1  31.633686     Tommy Hilfiger    Bottoms   Very Good  1.183242

   Review Count Style Attributes Total Sizes Available Sizes  Color  \
0           492       Streetwear    M, L, XL              XL  Green
1            57          Vintage    M, L, XL              XL  Black
2           197       Streetwear     S, M, L               M   Blue
3           473           Formal     S, M, L               L    Red
4            55           Sporty    M, L, XL               S  Green

  Purchase History  Age Fashion Magazines Fashion Influencers       Season  \
0           Medium   24             Vogue     Chiara Ferragni  Fall/Winter
1    Above Average   61           Glamour      Leandra Medine       Winter
2          Average   27      Marie Claire          Gigi Hadid       Summer
3        Very High   50      Marie Claire     Chiara Ferragni  Fall/Winter
4    Above Average   23           Glamour       Song of Style       Spring

  Time Period Highest Purchase Customer Reviews Social Media Comments  \
0                      Daytime            Mixed                 Mixed
1                      Weekend         Negative               Neutral
2                    Nighttime          Unknown              Negative
3                      Weekend          Neutral                 Other
4                      Daytime         Positive                 Mixed

   feedback
0     Other
1     Other
2   Neutral
3     Other
4  Positive

Informations sur les types de données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 20 columns):
 #   Column                        Non-Null Count    Dtype
---  ------                        --------------    -----
 0   Product Name                  1000000 non-null  object
 1   Price                         1000000 non-null  float64
 2   Brand                         1000000 non-null  object
 3   Category                      1000000 non-null  object
 4   Description                   1000000 non-null  object
 5   Rating                        1000000 non-null  float64
 6   Review Count                  1000000 non-null  int64
 7   Style Attributes              1000000 non-null  object
 8   Total Sizes                   1000000 non-null  object
 9   Available Sizes               1000000 non-null  object
 10  Color                         1000000 non-null  object
 11  Purchase History              1000000 non-null  object
 12  Age                           1000000 non-null  int64
 13  Fashion Magazines             1000000 non-null  object
 14  Fashion Influencers           1000000 non-null  object
 15  Season                        1000000 non-null  object
 16  Time Period Highest Purchase  1000000 non-null  object
 17  Customer Reviews              1000000 non-null  object
 18  Social Media Comments         1000000 non-null  object
 19  feedback                      1000000 non-null  object
dtypes: float64(2), int64(2), object(16)
memory usage: 152.6+ MB
None

In [24]:
# Cellule 1 : Imports
import pandas as pd
import numpy as np

# Cellule 2 : Chargement des données
print("Chargement des données...")
df_mock = pd.read_csv('../data/stats/mock_fashion_data_uk_us.csv')

print("\nAperçu initial:")
print(f"Nombre de lignes: {len(df_mock)}")
print(f"Colonnes présentes:")
print(df_mock.columns.tolist())

# Cellule 3 : Nettoyage des colonnes numériques
numeric_columns = ['Price', 'Rating', 'Review Count', 'Age']
for col in numeric_columns:
    if col in df_mock.columns:
        df_mock[col] = pd.to_numeric(df_mock[col], errors='coerce')
        df_mock = df_mock[df_mock[col] >= 0]

print("\nStatistiques des colonnes numériques après nettoyage:")
print(df_mock[numeric_columns].describe())

# Cellule 4 : Nettoyage des colonnes textuelles
text_columns = ['Product Name', 'Brand', 'Category', 'Description', 'Style Attributes',
                'Fashion Magazines', 'Fashion Influencers']

for col in text_columns:
    if col in df_mock.columns:
        df_mock[col] = df_mock[col].str.strip()
        df_mock[col] = df_mock[col].str.title()

# Cellule 5 : Standardisation des catégories
category_mapping = {
    'Footwear': 'Shoes',
    'Tops': 'Top',
    'Outerwear': 'Outerwear',
    'Bottoms': 'Bottom'
}
df_mock['Category'] = df_mock['Category'].map(category_mapping).fillna(df_mock['Category'])

# Cellule 6 : Nettoyage des tailles
def clean_sizes(sizes_str):
    if pd.isna(sizes_str):
        return ''
    # Retourner une chaîne de caractères au lieu d'une liste
    sizes = [size.strip() for size in str(sizes_str).split(',')]
    return ', '.join(sorted(sizes))

# Appliquer le nettoyage et conserver comme chaîne de caractères
df_mock['Total Sizes'] = df_mock['Total Sizes'].apply(clean_sizes)
df_mock['Available Sizes'] = df_mock['Available Sizes'].str.strip()

# Cellule 7 : Standardisation des évaluations
rating_mapping = {
    'Very Bad': 1,
    'Bad': 2,
    'Not Good': 3,
    'Good': 4,
    'Very Good': 5
}
df_mock['Rating_Numeric'] = df_mock['Rating'].map(rating_mapping).fillna(df_mock['Rating'])

# Cellule 8 : Standardisation des saisons
season_mapping = {
    'Fall/Winter': 'FW',
    'Winter': 'W',
    'Summer': 'S',
    'Spring': 'SP'
}
df_mock['Season'] = df_mock['Season'].map(season_mapping).fillna(df_mock['Season'])

# Cellule 9 : Gestion des valeurs manquantes
# Pour les colonnes numériques
numeric_columns = df_mock.select_dtypes(include=[np.number]).columns
for col in numeric_columns:
    df_mock[col] = df_mock[col].fillna(df_mock[col].median())

# Pour les colonnes catégorielles
categorical_columns = df_mock.select_dtypes(include=['object']).columns
for col in categorical_columns:
    df_mock[col] = df_mock[col].fillna('Unknown')

# Cellule 10 : Suppression des doublons
print("\nNombre de lignes avant suppression des doublons:", len(df_mock))
df_mock = df_mock.drop_duplicates()
print("Nombre de lignes après suppression des doublons:", len(df_mock))

# Cellule 11 : Vérification finale et sauvegarde
print("\nAperçu final des données nettoyées:")
print(df_mock.head())
print("\nInformations sur les données:")
print(df_mock.info())

# Sauvegarde des données nettoyées
output_path = '../data/stats/mock_fashion_data_cleaned.csv'
df_mock.to_csv(output_path, index=False)
print(f"\nDonnées nettoyées sauvegardées dans: {output_path}")

Chargement des données...

Aperçu initial:
Nombre de lignes: 1000000
Colonnes présentes:
['Product Name', 'Price', 'Brand', 'Category', 'Description', 'Rating', 'Review Count', 'Style Attributes', 'Total Sizes', 'Available Sizes', 'Color', 'Purchase History', 'Age', 'Fashion Magazines', 'Fashion Influencers', 'Season', 'Time Period Highest Purchase', 'Customer Reviews', 'Social Media Comments', 'feedback']

Statistiques des colonnes numériques après nettoyage:
                Price          Rating    Review Count             Age
count  1000000.000000  1000000.000000  1000000.000000  1000000.000000
mean        55.001428        2.998454      249.602431       41.004191
std         25.979720        1.154696      144.362645       13.565907
min         10.000145        1.000000        0.000000       18.000000
25%         32.496717        1.998608      125.000000       29.000000
50%         55.007413        2.996328      249.000000       41.000000
75%         77.511242        3.998479      375.000000       53.000000
max         99.999648        4.999999      499.000000       64.000000

Nombre de lignes avant suppression des doublons: 1000000
Nombre de lignes après suppression des doublons: 1000000

Aperçu final des données nettoyées:
  Product Name      Price              Brand   Category Description    Rating  \
0         T5D3  97.509966       Ralph Lauren      Shoes         Bad  1.421706
1         Y0V7  52.341277          Ted Baker        Top    Not Good  1.037677
2         N9Q4  15.430975             Jigsaw      Shoes    Very Bad  3.967106
3         V2T6  81.116542  Alexander Mcqueen  Outerwear    Not Good  2.844659
4         S7Y1  31.633686     Tommy Hilfiger     Bottom   Very Good  1.183242

   Review Count Style Attributes Total Sizes Available Sizes  ...  \
0           492       Streetwear    L, M, XL              XL  ...
1            57          Vintage    L, M, XL              XL  ...
2           197       Streetwear     L, M, S               M  ...
3           473           Formal     L, M, S               L  ...
4            55           Sporty    L, M, XL               S  ...

  Purchase History Age  Fashion Magazines Fashion Influencers Season  \
0           Medium  24              Vogue     Chiara Ferragni     FW
1    Above Average  61            Glamour      Leandra Medine      W
2          Average  27       Marie Claire          Gigi Hadid      S
3        Very High  50       Marie Claire     Chiara Ferragni     FW
4    Above Average  23            Glamour       Song Of Style     SP

  Time Period Highest Purchase Customer Reviews Social Media Comments  \
0                      Daytime            Mixed                 Mixed
1                      Weekend         Negative               Neutral
2                    Nighttime          Unknown              Negative
3                      Weekend          Neutral                 Other
4                      Daytime         Positive                 Mixed

   feedback Rating_Numeric
0     Other       1.421706
1     Other       1.037677
2   Neutral       3.967106
3     Other       2.844659
4  Positive       1.183242

[5 rows x 21 columns]

Informations sur les données:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 21 columns):
 #   Column                        Non-Null Count    Dtype
---  ------                        --------------    -----
 0   Product Name                  1000000 non-null  object
 1   Price                         1000000 non-null  float64
 2   Brand                         1000000 non-null  object
 3   Category                      1000000 non-null  object
 4   Description                   1000000 non-null  object
 5   Rating                        1000000 non-null  float64
 6   Review Count                  1000000 non-null  int64
 7   Style Attributes              1000000 non-null  object
 8   Total Sizes                   1000000 non-null  object
 9   Available Sizes               1000000 non-null  object
 10  Color                         1000000 non-null  object
 11  Purchase History              1000000 non-null  object
 12  Age                           1000000 non-null  int64
 13  Fashion Magazines             1000000 non-null  object
 14  Fashion Influencers           1000000 non-null  object
 15  Season                        1000000 non-null  object
 16  Time Period Highest Purchase  1000000 non-null  object
 17  Customer Reviews              1000000 non-null  object
 18  Social Media Comments         1000000 non-null  object
 19  feedback                      1000000 non-null  object
 20  Rating_Numeric                1000000 non-null  float64
dtypes: float64(3), int64(2), object(16)
memory usage: 160.2+ MB
None

Données nettoyées sauvegardées dans: ../data/stats/mock_fashion_data_cleaned.csv

In [25]:
# Cellule 1 : Imports
import pandas as pd
import numpy as np

# Cellule 2 : Chargement des données
print("Chargement des données...")
input_path = '../data/trends/googletrends01_20.csv'  # Modifier avec le chemin correct si nécessaire
df_trends = pd.read_csv(input_path)

print("\nAperçu initial:")
print(f"Nombre de lignes: {len(df_trends)}")
print(f"Colonnes présentes:")
print(df_trends.columns.tolist())

# Cellule 3 : Nettoyage des colonnes numériques
numeric_columns = ['rank', 'year']
for col in numeric_columns:
    if col in df_trends.columns:
        df_trends[col] = pd.to_numeric(df_trends[col], errors='coerce')
        df_trends = df_trends[df_trends[col] >= 0]

print("\nStatistiques des colonnes numériques après nettoyage:")
print(df_trends[numeric_columns].describe())

# Cellule 4 : Nettoyage des colonnes textuelles
text_columns = ['location', 'category', 'query']
for col in text_columns:
    if col in df_trends.columns:
        df_trends[col] = df_trends[col].str.strip()  # Supprime les espaces inutiles
        df_trends[col] = df_trends[col].str.title()  # Uniformise la casse

# Cellule 5 : Gestion des valeurs manquantes
# Pour les colonnes numériques
numeric_columns = df_trends.select_dtypes(include=[np.number]).columns
for col in numeric_columns:
    df_trends[col] = df_trends[col].fillna(df_trends[col].median())

# Pour les colonnes catégorielles
categorical_columns = df_trends.select_dtypes(include=['object']).columns
for col in categorical_columns:
    df_trends[col] = df_trends[col].fillna('Unknown')

# Cellule 6 : Suppression des doublons
print("\nNombre de lignes avant suppression des doublons:", len(df_trends))
df_trends = df_trends.drop_duplicates()
print("Nombre de lignes après suppression des doublons:", len(df_trends))

# Cellule 7 : Vérification finale et sauvegarde
print("\nAperçu final des données nettoyées:")
print(df_trends.head())
print("\nInformations sur les données:")
print(df_trends.info())

# Sauvegarde des données nettoyées
output_path = '../data/trends/googletrends_cleaned.csv'
df_trends.to_csv(output_path, index=False)
print(f"\nDonnées nettoyées sauvegardées dans: {output_path}")

Chargement des données...

Aperçu initial:
Nombre de lignes: 26955
Colonnes présentes:
['location', 'year', 'category', 'rank', 'query']

Statistiques des colonnes numériques après nettoyage:
              rank          year
count  26955.00000  26955.000000
mean       3.00000   2015.243369
std        1.41424      3.564683
min        1.00000   2001.000000
25%        2.00000   2013.000000
50%        3.00000   2016.000000
75%        4.00000   2018.000000
max        5.00000   2020.000000

Nombre de lignes avant suppression des doublons: 26955
Nombre de lignes après suppression des doublons: 26945

Aperçu final des données nettoyées:
  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    Bmw
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

Informations sur les données:
<class 'pandas.core.frame.DataFrame'>
Index: 26945 entries, 0 to 26954
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  26945 non-null  object
 1   year      26945 non-null  int64
 2   category  26945 non-null  object
 3   rank      26945 non-null  int64
 4   query     26945 non-null  object
dtypes: int64(2), object(3)
memory usage: 1.2+ MB
None

Données nettoyées sauvegardées dans: ../data/trends/googletrends_cleaned.csv